# -*- coding: utf-8 -*-
"""NLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gwUTNoeNGZ3Ud3uriRR0B9s9kPA-mIJz
"""

from datetime import datetime
startTime = datetime.now()

LINKS = []
HASH_TAGS = []

WORDS = []

import pandas as pd
import numpy as np

df= pd.read_csv(r"C:\Users\Pravallika Myneni\Desktop\replies.csv")

df['no_of_mentions'] = df['text'].str.count("@")



df['tags_removed'] = df['text'].apply(lambda x : x[x.find(" ")+1: ]+" " )


"""## Removing Mentions"""

df['tags_removed'] =  df['tags_removed'].apply(lambda x: x[x.find(" ")+1: ] if ("@" in x) else x)


"""### Removing links"""

for x in df['tags_removed']:
  if ("http" in x):
    link = x[x.find("http") : x.find(" ")+1]
    #print(link)
    LINKS.append(link)

df['links_removed'] =  df['tags_removed'].apply(lambda x: x[x.find(" ")+1: ] if ("http" in x) else x)


df = df.drop(columns=['tags_removed', 'no_of_mentions'])


"""Dropping null rows"""

df['links_removed'].apply(lambda x: len(x))

df = df.replace("", np.nan)

df = df.dropna(subset=['links_removed'])




## Word Cloud

###**Using the key Phrase extraction feature**


import os
os.environ["EAI_USERNAME"] = 'mynenisp1703@gmail.com'
os.environ["EAI_PASSWORD"] = 'Ready@hack1'

from expertai.nlapi.cloud.client import ExpertAiClient
client = ExpertAiClient()
language = "en"

"""document = client.specific_resource_analysis(
    body={"document": {"text": df.loc[0,'links_removed']}}, 
    params={'language': language, 'resource': 'relevants'})

print (f'{"LEMMA":{20}} {"SCORE":{5}} ')
       
for mainlemma in document.main_lemmas:
    print (f'{mainlemma.value:{20}} {mainlemma.score:{5}}')

For each row
"""

All_sentences = list(df['links_removed'])
All_sentences

for sentence in All_sentences:
  document = client.specific_resource_analysis(
    body={"document": {"text": sentence }}, 
    params={'language': language, 'resource': 'relevants'})
  for mainlemma in document.main_lemmas:
    WORDS.append(mainlemma.value)


import numpy as np
import matplotlib.pyplot as plt
import re
from PIL import Image
from wordcloud import WordCloud, STOPWORDS
from IPython.display import Image as im

mask = np.array(Image.open(r'C:\Users\Pravallika Myneni\Desktop\twitter mask.jpg'))

wc = WordCloud(background_color="white", max_words=2000, mask=mask)
clean_string = ','.join(WORDS)
wc.generate(clean_string)

plt.figure(figsize=(20,20))
plt.imshow(wc, interpolation='bilinear')
plt.axis("off")
plt.show()

print(datetime.now() - startTime)